import { useEffect, useRef, useState } from "react";
import HouseRow from "./house-row/HouseRow";
import AddHouseButton from "./AddHouseButton";

export interface House {
    id?: number;
    address: string;
    country: string;
    price: number;
    photo?: string;
    description?: string;
};

/**
 * HouseList is its own component and needs its own props type
 */
export interface HouseListProps {
    selectHouse: (house: House) => void;
  }

const HouseList = ({selectHouse}: HouseListProps) => {
    /**
     * Using the useState hook (a function).
     * Its first parameter is the initial value of the state.
     * useState returns an array
     */
    const [houses, setHouses] = useState<House[]>([]);
    
    const counter = useRef(0);

    /**
     * This effect runs only once when the component mounts (because of the empty [] dependency array).
     * It fetches the current list of houses from the backend.
     * Once the JSON is received, it updates the houses state.
     */
    useEffect(() => {
        const fetchHouses = async () => {
            const response: Response = await fetch("https://localhost:4000/house");
            const houses = (await response).json();
            setHouses(await houses);
        };
        fetchHouses();
        
        // When a reference type is passed to useRef, the ref hook guarantees that
        // the same reference is returned in the current property across re-renders.
        counter.current++;
    }, []);

    /**
     * This function prepares a new house to add.
     * We use Omit<House, "id"> because the ID will be generated by the backend. 
     */
    const addHouse = async () => {
        const newHouse: Omit<House, "id"> = {
            address: "32 Valley Way, New York",
            country: "USA",
            price: 1000000          
        };

        /**
         * This performs a POST request to add the house.
         * The body is converted to JSON using JSON.stringify.
         */
        const response = await fetch("https://localhost:4000/house", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(newHouse)
        });

        /**
         * Once the backend returns the newly created house, we add it to the
         * existing state using the spread operator (...houses)
         */
        const createdHouse: House = await response.json();
        setHouses([...houses, createdHouse]); 
    };

    return (
        <>
            <div className="row mb-2">
                <h5 className="themeFontColor text-center">
                    Houses currently on the market
                </h5>
            </div>
            <table className="table table-hover">
                <thead>
                    <tr>
                        <th>Address</th>
                        <th>Country</th>
                        <th>Asking Price</th>
                    </tr>
                </thead>
                <tbody>
                    {houses.map(h => <HouseRow key={h.id} house={h} selectHouse={selectHouse}/>)}
                </tbody>
            </table>
            <AddHouseButton onAddHouse={addHouse}/>
        </>
    );
};

export default HouseList;